# Generated by Django 4.1.7 on 2023-02-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified_email",
            field=models.BooleanField(default=False),
        ),
    ]
